1 Semestre/Backend-2/Projeto-Gamer-MVC/Models/Equipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Projeto_Gamer.Models
{
    public class Equipe
    {
        [Key]
        public int IdEquipe { get; set; }
        public string? Nome { get; set; }
        public string? Imagem { get; set; }

        public ICollection<Jogador>? Jogador { get; set; }
    }
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Models/ErrorViewModel.cs
namespace Projeto_Gamer.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Models/Jogador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Projeto_Gamer.Models
{
    public class Jogador
    {
        [Key]
        public int IdJogador { get; set; }
        public string? Nome { get; set; }
        public string? Email { get; set; }
        public string? Senha { get; set; }
        public Equipe? Equipe { get; set; }

        [ForeignKey("Equipe")]
        public int IdEquipe { get; set; }

    }
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Projeto_Gamer.Models;

namespace Projeto_Gamer.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        ViewBag.UserName = HttpContext.Session.GetString("UserName");
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Controllers/JogadorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Projeto_Gamer.infra;
using Projeto_Gamer.Models;

namespace Projeto_Gamer.Controllers
{
    [Route("[controller]")]
    public class JogadorController : Controller
    {
        private readonly ILogger<JogadorController> _logger;

        public JogadorController(ILogger<JogadorController> logger)
        {
            _logger = logger;
        }

        Context c = new Context();

        [Route("Listar")]
        public IActionResult Index() {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            ViewBag.Jogador = c.Jogador.ToList();
            ViewBag.Equipe = c.Equipe.ToList();

            return View();
        }

        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form) {

            Jogador novoJogador = new Jogador();

            novoJogador.Nome = form["Nome"].ToString();
            novoJogador.Email = form["Email"].ToString();
            novoJogador.Senha = form["Senha"].ToString();
            novoJogador.IdEquipe = int.Parse(form["Equipe"]!);
            

            c.Add(novoJogador);

            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        [Route("Atualizar")]
        public IActionResult Atualizar(IFormCollection form) {
                
            Jogador novoJogador = new Jogador();
            
            novoJogador.IdJogador = int.Parse(form["IdJogador"]!);
            novoJogador.Nome = form["Nome"].ToString();
            novoJogador.Email = form["Email"].ToString();
            novoJogador.Senha = form["Senha"].ToString();
            novoJogador.IdEquipe = int.Parse(form["IdEquipe"]!);
            
            Jogador jogadorbuscado = c.Jogador.First(j => j.IdJogador == novoJogador.IdJogador);

            jogadorbuscado.IdEquipe = novoJogador.IdEquipe;
            jogadorbuscado.Nome = novoJogador.Nome;
            jogadorbuscado.Email = novoJogador.Email;
            jogadorbuscado.Senha = novoJogador.Senha;
            

            c.Jogador.Update(jogadorbuscado);

            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }

        [Route("Excluir{id}")]

        public IActionResult Excluir(int id){
            Jogador e = c.Jogador.First(e => e.IdJogador == id);

            c.Jogador.Remove(e);

            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }

        [Route("Editar{id}")]

        public IActionResult Editar(int id) {
            Jogador e = c.Jogador.First(e => e.IdJogador == id);
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            ViewBag.Jogador = e;

            ViewBag.Equipe = c.Equipe.ToList();

            return View("Editar");
        }
    }
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Projeto_Gamer.infra;
using Projeto_Gamer.Models;

namespace Projeto_Gamer.Controllers
{
    [Route("[controller]")]
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }


        [Route("Login")]
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error");
        }

        [TempData]

        public string Message { get; set; }
        Context c = new Context();

        [Route("Logar")]
        public IActionResult Logar(IFormCollection form) {

            string email = form["Email"].ToString();
            string senha = form["Senha"].ToString();

            Jogador jogadorBuscado = c.Jogador.FirstOrDefault(j => j.Email == email && j.Senha == senha)!;

            if (jogadorBuscado != null) {

                HttpContext.Session.SetString("UserName", jogadorBuscado.Nome!);
                return LocalRedirect("~/");

            }
            else {
                Message = "Dados inválidos, tente novamente!!!";
                return LocalRedirect("~/Login/Login");
            }
        }

        [Route("Logout")] 

        public IActionResult Logout() 
        {
            HttpContext.Session.Remove("UserName");
            return LocalRedirect("~/");         
        }
    }
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Views/Equipe/Edit.cshtml
@model Equipe

@{
    ViewData["Title"] = "Edit";
}

<link rel="stylesheet" href="~/css/equipes.css">

@if (ViewBag.UserName == null)
{
    <a class="navbar-brand" asp-controller="Login" asp-action="Index">Login</a>
}else {
    <section class="container-grid cadastro-equipes">
    <form method="post" action="@Url.Action("Atualizar")" enctype="multipart/form-data" class="frm-cad-equipe">
        <div class="cadequipe-titulo">
            <h1>Editar de Equipes</h1>
            <hr>
        </div>


        <input type="hidden" name="IdEquipe" value="@ViewBag.Equipe.IdEquipe">
        <input type="text" name="Nome" class="campo-entrada" placeholder="Digite o nome da sua equipe:">
        <label class="foto" for="foto-file">
            <input input type="file" name="Imagem" id="foto-file">
        </label>

        <button type="submite">Atualizar</button>
    </form>
</section>
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Views/Equipe/Index.cshtml
@model Equipe
@{
    ViewData["Title"] = "Equipes";
}

<head>
    <link rel="stylesheet" href="~/css/equipes.css">
</head>

@if (ViewBag.UserName == null)
{
    <section class="container-grid cadastro-equipes">
        <div class="frm-cad-equipe">
            <div class="cadequipe-titulo">
                <h1>Login não realizado</h1>
                <hr>
            </div>
            <p style="font-size: 17px;" class="card-text">Faça o login para poder acessar o conteúdo requisitado</p>
            <div class="nlog-btns">
                <a asp-controller="Login" asp-action="Index" class="card-link">Login</a>
                <a class="card-link" asp-controller="Home" asp-action="Index">Home</a>
            </div>
        </div>
    </section>
}


else
{
    <section class="container-grid cadastro-equipes">


        <form method="post" action="@Url.Action("Cadastrar")" enctype="multipart/form-data" class="frm-cad-equipe">
            <div class="cadequipe-titulo">
                <h1>Cadastro de Equipes</h1>
                <hr>
            </div>

            <input type="text" name="Nome" class="campo-entrada" placeholder="Digite o nome da sua equipe:">
            <label class="foto" for="foto-file">
                <input input type="file" name="Imagem" id="foto-file">
            </label>

            <button type="submite">Cadastro</button>
        </form>



        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Foto</th>
                    <th>&spades;</th>
                </tr>
            </thead>
            <tbody>
                <div class="overflow-y-auto" style="max-height: 250px;">
                    @foreach (Equipe equipe in ViewBag.Equipe)
                    {
                        <tr>
                            <td>@equipe.IdEquipe</td>
                            <td>@equipe.Nome</td>
                            <td><img src="/img/Equipe/@equipe.Imagem" alt="" width="50px"></td>
                            <td style="gap: 10px"><a asp-area="" asp-controller="Equipe" asp-action="Excluir"
                                    asp-route-id="@equipe.IdEquipe"><img class="yellow-trash" src="~/assets/trash.png"
                                        alt=""></a>
                                <a asp-area="" asp-controller="Equipe" asp-action="Editar" asp-route-id="@equipe.IdEquipe"><img
                                        src="~/assets/edit-3-xxl.png" alt="" width="20px"></a>
                            </td>
                        </tr>
                    }
                </div>
            </tbody>
        </table>
    </section>
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="~/css/home.css">

<section class="banner">
        <h2>Liga Gamers</h2>
        <a href="#" class="btn-sobreliga">Sobre</a>
    </section>

    <!-- CARD JOGOS -->
    <section >
        <div class="container-grid card-jogos">
            <img src="~/assets/images/Game-FIFA.png" alt="Fifa 23">
            <img src="~/assets/images/Game-CS-GO.png" alt="Úlimo Jogo">
        </div>
    </section>

    <!-- PROGAMER -->
    <section class="progamer">
        <div class="container-grid progamer-flex">
            <div class="progamer-title">
                <h2>Entre para o time progamer</h2>
                <hr>
            </div>

            <!-- efeito borda gradient -->
            <div class="gamers">
                <img src="~/assets/images/kiljoy.png" alt="Gamer 1">
                <div class="card-bkg" id="jogos-diferentes">
                    <article class="produto">
                        <img src="~/assets/joystick-icon.svg" alt="Icone Joystick">
                        <h3>20 Jogos Diferentes</h3>
                        <p>São mais de 20 jogos em 2 plataformas dispóniveis para que você possa aprender melhores
                            técnicas.</p>
                    </article>
                </div>
            </div>

            <div class="gamers">
                <img src="~/assets/images/lade-lol.png" alt="Gamer 2">
                <div class="card-bkg" id="professores">
                    <article class="produto">
                        <img src="~/assets/joystick-prof-icon.svg" alt="Icone Joystick">
                        <h3>53 Professores</h3>
                        <p>Temos 53 Proplayers no nosso time para ensinar todas as es- tratégias, você vai aprender do
                            básico ao avançado. <br>
                            Tempo de treinamento, des- canso, equipamentos.</p>
                    </article>
                </div>
            </div>
        </div>
    </section>

    <!-- NOTÍCIAS -->
    <section class="noticias" id="noticias">
        <div class="container-grid noticias-flex">
            <div>
                <h2>Notícias</h2>
                <hr>
            </div>

            <article class="card-noticia">
                <img src="~/assets/images/noticia1.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>

            <article class="card-noticia">
                <img src="~/assets/images/noticia2.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>

            <article class="card-noticia">
                <img src="~/assets/images/noticia3.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>

            <article class="card-noticia">
                <img src="~/assets/images/noticia4.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>

            <article class="card-noticia">
                <img src="~/assets/images/noticia5.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>

            <article class="card-noticia">
                <img src="~/assets/images/noticia6.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>

            <article class="card-noticia">
                <img src="~/assets/images/noticia7.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>

            <article class="card-noticia">
                <img src="~/assets/images/noticia8.png" alt="Notícia 1">
                <h3>Título da Notícia</h3>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                    industry's standard dummy text ever since.</p>
            </article>
        </div>
    </section>

1 Semestre/Backend-2/Projeto-Gamer-MVC/Views/Jogador/Index.cshtml
@model Jogador
@{
    ViewData["Title"] = "Jogadores";
}

<link rel="stylesheet" href="~/css/jogadores.css">


@if (ViewBag.UserName == null)
{
    <section class="container-grid cadastro-equipes">
        <div class="frm-cad-equipe">
            <div class="cadequipe-titulo">
                <h1>Login não realizado</h1>
                <hr>
            </div>
            <p style="font-size: 17px;" class="card-text">Faça o login para poder acessar o conteúdo requisitado</p>
            <div class="nlog-btns">
                <a asp-controller="Login" asp-action="Index" class="card-link">Login</a>
                <a class="card-link" asp-controller="Home" asp-action="Index">Home</a>
            </div>
        </div>
    </section>
}

else
{
    <section class="container-grid cadastro-equipes">
        <form method="post" action="@Url.Action("Cadastrar")" enctype="multipart/form-data" class="frm-cad-equipe">
            <div class="cadequipe-titulo">
                <h1>Cadastro de Jogadores</h1>
                <hr>
            </div>

            <select class="campo-entrada" id="equipe-select" aria-label="Default select example" name="Equipe">
                <option style="background-color: transparent;" selected>Selecione uma Equipe</option>
                @foreach (Equipe equipe in ViewBag.Equipe)
                {
                    <option style="background-color: transparent;" value=@equipe.IdEquipe>@equipe.Nome</option>
                }
            </select>
            <input class="campo-entrada" type="text" name="Nome" id="nome-jogador" placeholder="Digite o nome do Jogador:">
            <input class="campo-entrada" type="email" name="Email" id="email-jogador"
                placeholder="Digite o Email do Jogador:">
            <input class="campo-entrada" type="password" name="Senha" id="senha" placeholder="Digite a Senha:">
            <button>Cadastrar</button>




        </form>

        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Equipe</th>
                    <th>&spades;</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Jogador jogador in ViewBag.Jogador)
                {
                    <tr>
                        <td>@jogador.IdJogador</td>
                        <td>@jogador.Nome</td>
                        <td>@jogador.Email</td>
                        <td><img src="/img/Equipe/@jogador.Equipe.Imagem" alt="" width="50px"></td>
                        <td style="gap: 20px;">
                            <a asp-area="" asp-controller="Jogador" asp-action="Excluir" asp-route-id="@jogador.IdJogador"><img class="yellow-trash" src="~/assets/trash.png" alt=""></a>
                            <a asp-area="" asp-controller="Jogador" asp-action="Editar" asp-route-id="@jogador.IdJogador"><img src="~/assets/edit-3-xxl.png" alt="" width="20px"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </section>
}

1 Semestre/Backend-2/Projeto-Gamer-MVC/Views/Login/Index.cshtml
@model Jogador

@{
    ViewData["Title"] = "Login";
}

<head>
    <link rel="stylesheet" href="~/css/login.css">
</head>

<!-- FORMULÁRIO DE LOGIN -->
<main class="fundo-login">
    <div class="bkg-login">
        <form class="frm-login" method="post" action="@Url.Action("Logar")" enctype="multipart/form-data">
            <div class="login-title">
                <hr class="login-line">
                <h1>Login</h1>
            </div>
            <div class="frm-linha">
                <div class="bkg-input">
                    <img src="~/assets/vector-user.svg" alt="ícone de usuário">
                    <input required type="email" name="Email" id="email" placeholder="Digite seu e-mail:">
                </div>
            </div>
            <div class="frm-linha">
                <div class="bkg-input">
                    <img src="~/assets/vector-key.svg" alt="ícone de chave">
                    <input required type="password" name="Senha" id="password" placeholder="Digite sua senha:">
                </div>
            </div>

            <button class="btn-logar" type="submit">Logar</button>
        </form>
    </div>

</main>

1 Semestre/Backend-2/Projeto-Gamer-MVC/Views/Shared/_Layout.Backup.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_Gamer</title>
</head>

<body>
    <!-- HEADER -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto_Gamer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewBag.UserName != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Equipe"
                                    asp-action="Index">Cadastro de Equipe</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Jogador"
                                    asp-action="Index">Cadastro de Jogadores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login"
                                    asp-action="Logout">Logout</a>
                            </li>
                            <li>
                                <p class="nav-link text-dark">Olá, @ViewBag.UserName</p>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login"
                                    asp-action="Index">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

1 Semestre/Backend-2/Projeto-Gamer-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_Gamer</title>
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/header-footer.css">
</head>

<body>

    <header class="header">
        <div class="header-top">
            <div class="container-grid header-top-flex">
                <div>
                    <span class="phone-box">
                        <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                        (11) 0900-1010
                    </span>

                    <span class="mail-box">
                        <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                        contato@gamer.com.br
                    </span>
                </div>

                <span class="social-box">
                    <a href="#"><img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone"></a>
                    <a href="#"><img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone"></a>
                    <a href="#"><img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone"></a>
                </span>
            </div>
        </div>
        <div class="header-bottom">
            <div class="container-grid header-bottom">
                <label for="mostra-esconde-navmenu"><img src="~/assets/menu-hamburger.svg" alt="Menu Hamburger"
                        title="Ícone Menu">
                </label>


                <h1>
                    <span class="title">Gamer</span>
                    <img src="~/assets/logotipo-gamer.svg" id="logotipo" alt="Logotipo Gamer" title="Gamer Logotipo">
                </h1>

                <input type="checkbox" id="mostra-esconde-navmenu">
                <div class="nav-bkg">
                    <nav>
                        <a asp-controller="Home" asp-action="Index">Início</a>
                        @if (ViewBag.UserName != null)
                        {
                            <a asp-controller="Jogador" asp-action="Index">Jogadores</a>
                            <a asp-controller="Equipe" asp-action="Index">Equipes</a>
                            <a asp-controller="Login" asp-action="Logout">Logout</a>
                        }
                        <a href="~/#noticias">Notícias</a>

                        <a class="phone-box">
                            <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                            (11) 0900-1010
                        </a>
                        <a class="mail-box">
                            <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                            contato@gamer.com.br
                        </a>

                        <!-- social icons -->
                        <span class="social-box">
                            <a href="#"><img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone"></a>
                            <a href="#"><img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone"></a>
                            <a href="#"><img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone"></a>
                        </span>
                    </nav>
                </div>
                <!-- Header Menu Ícones laterais -->
                <label for="mostra-esconde-icones">
                    <img src="~/assets/menu-points.png" alt="Menu Points">
                </label>

                <input type="checkbox" id="mostra-esconde-icones">
                <div class="icons-header-bkg">
                    <div class="icons-header">
                        <a asp-controller="Login" asp-action="Index"><img src="~/assets/user-icon.svg" alt="user-login"></a>
                        <a href=""><img src="~/assets/market-icon.png" alt="market icon"></a>
                        <a href=""><img src="~/assets/search-icon.png" alt="search icon"></a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- FOOTER -->
    <footer>
        <div class="container-grid footer-flex">

            <div class="card-ftitem-box">
                <a href="#" id="ftlogo-link">
                    <img src="~/assets/logotipo-gamer.svg" id="ftlogo" alt="Home">
                </a>
                <p>Nosso sucesso na criação de soluções de negócios se deve em grande parte à nossa equipe talentosa e
                    altamente comprometida.</p>
                <div class="social-fticons">
                    <a href="#">
                        <img src="~/assets/facebook-yellow.svg" alt="Icone Facebook">
                    </a>
                    <a href="#">
                        <img src="~/assets/linkedin-yellow.svg" alt="Icone Linkedin">
                    </a>
                    <a href="#">
                        <img src="~/assets/instagram-yellow.svg" alt="Icone instagram">
                    </a>
                </div>
            </div>


            <div class="card-ftitem-box">
                <div>
                    <h2>Links Úteis</h2>
                    <hr>
                </div>

                <ul class="menu-footer">
                    <li class="menu-ftitem"><a asp-controller="Home" asp-action="Index">Início</a></li>
                    <li class="menu-ftitem"><a asp-controller="Jogador" asp-action="Index">Jogadores</a></li>
                    <li class="menu-ftitem"><a href="~/#noticias">Notícias</a></li>
                    @if(ViewBag.UserName != null) {
                        <li class="menu-ftitem"><a asp-controller="Login" asp-action="Logout">Logout</a></li>
                    }else {
                        <li class="menu-ftitem"><a asp-controller="Login" asp-action="Login">Login</a></li>
                    }
                    <li class="menu-ftitem" id="link-equipe"><a asp-controller="Equipe" asp-action="Index">Equipes</a></li>
                </ul>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Contatos</h2>
                    <hr>
                </div>

                <div>
                    <p class="contact-title">Localização:</p>
                    <p class="contact-text">Rua Niterói, 180 - São Caetano do Sul - SP</p>

                    <p class="contact-title">Junte-se a nós:</p>
                    <p class="contact-text"><a href="mailto:contato">contato@gamer.com.br</a></p>

                    <p class="contact-title">Telefone:</p>
                    <p class="contact-text">(11) 0900-1010</p>
                </div>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Newsletter</h2>
                    <hr>
                </div>

                <form action="" class="frm-news">
                    <div class="input-box">
                        <input type="text" class="frm-input" placeholder="Digite seu email:">
                    </div>
                    <button type="button" class="frm-button">Enviar</button>
                </form>
            </div>

        </div>

        <div id="copyright">
            &#169;Copyright2022-GamerJogosDigitais
        </div>

        <img src="~/assets/Botao_voltar_ao_topo.svg" id="back-to-top" alt="Voltar ao Topo">
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>